### ISSUE TITLE
재미있어요!

### ISSUE THREAD

**Issue by DongGeon0908** [leegeunhyeok/army-gardener#1]
깃허브 구경하다가 들렸는데, 재미있는 저장소 같아요~
기발한 아이디어 같아 이슈 날려요! 멋집니다!
군대생활 잘 갔다오세요!~~ 화이팅입니다!

**Comment by leegeunhyeok** [comment]
25일 오늘 수료하고 나왔습니다☺️☺️

감사합니다!!
